# From:
# https://github.com/rkdarst/sphinx-actions-test/blob/master/.github/workflows/sphinx-build.yml

# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: build-odoo-docs-ja
# on: [push, pull_request]
on: 
  workflow_dispatch:
    inputs:
      sourcecode:
        description: 'With inline docstrings'
        required: true
        default: '18.0' 
        type: choice
        options:
        - '18.0'
        - '17.0'
        - '16.0'
        - '15.0'
        - '14.0'
      branch:
        description: 'Target branch'
        required: true
        default: 'main'
        type: choice
        options:
        - 'main'
        - 'develop'
        - 'l10n_crowdin_action'
      python-version:
        description: 'Python version'
        required: true
        default: '3.8'
        type: choice
        options:
        - '3.12'
        - '3.10'
        - '3.8'
      checkout_odoo:
        description: 'Checkout odoo/odoo repository'
        required: false
        default: 'false'
        type: boolean

# https://gist.github.com/c-bata/ed5e7b7f8015502ee5092a3e77937c99
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout odoo/documentation
      - name: Checkout odoo/documentation
        uses: actions/checkout@v3
        with:
          repository: odoo/documentation
          ref: ${{ github.event.inputs.sourcecode }}
      # Checkout odoo-docs-src-locale-ja-xxx
      - name: Remove existing locale/ja if exists
        run: |
          rm -rf locale/ja
      - name: Checkout iroha-one/odoo-docs-src-locale-ja
        uses: actions/checkout@v3
        with:
          repository: iroha-one/odoo-docs-locale-ja-${{ github.event.inputs.sourcecode }}
          ref: ${{ github.event.inputs.branch }}
          path: locale/ja
      # Install Ptyhon and additional OS packages
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ github.event.inputs.python-version }}
      - name: Install additional OS packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libldap2-dev libsasl2-dev
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      # Optional: Checkout odoo/odoo
      - name: Checkout odoo/odoo
        if: ${{ github.event.inputs.checkout_odoo }}
        uses: actions/checkout@v3
        with:
          repository: odoo/odoo
          ref: ${{ github.event.inputs.sourcecode }}
          path: odoo
      - name: Install dependencies of odoo/odoo
        if: ${{ github.event.inputs.checkout_odoo }}
        run: |
          pip install -r odoo/requirements.txt
      # Build Sphinx docs for ja locale
      - name: Add 'ja' to languages_names in conf.py
        run: |
          echo -e "\n\nlanguages_names.setdefault('ja', '日本語')\n" >> conf.py
      - name: Build Sphinx docs
        run: |
          make html
        env:
          CURRENT_LANG: ja
      # https://github.com/marketplace/actions/github-pages
      #- if: success()
      #  uses: crazy-max/ghaction-github-pages@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    target_branch: gh-pages
      #    build_dir: _build/html/

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/ja/


# This action probably does everything for you:
# https://github.com/marketplace/actions/sphinx-build
