# Based on:
# https://github.com/rkdarst/sphinx-actions-test/blob/master/.github/workflows/sphinx-build.yml

# GitHub Actions workflow syntax reference:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: build-odoo-docs-ja
# on: [push, pull_request]
on: 
  workflow_dispatch:
    inputs:
      sourcecode:
        description: 'Odoo version'
        required: true
        default: '18.0' 
        type: choice
        options:
        - '18.0'
        - '17.0'
        - '16.0'
        - '15.0'
        - '14.0'
      branch:
        description: 'Target branch'
        required: true
        default: 'main'
        type: choice
        options:
        - 'main'
        - 'develop'
        - 'l10n_crowdin_action'
      python-version:
        description: 'Python version'
        required: true
        default: '3.9'
        type: choice
        options:
        - '3.12'
        - '3.11'
        - '3.10'
        - '3.9'
      checkout_odoo:
        description: 'Also checkout odoo/odoo repository'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Show workflow input values
      - name: WORKFLOW INPUTS
        run: |
          echo "sourcecode: ${{ github.event.inputs.sourcecode }}"
          echo "branch: ${{ github.event.inputs.branch }}"
          echo "python-version: ${{ github.event.inputs.python-version }}"
          echo "checkout_odoo: ${{ github.event.inputs.checkout_odoo }}"
      # Checkout odoo/documentation repository
      - name: Checkout odoo/documentation
        uses: actions/checkout@v3
        with:
          repository: odoo/documentation
          ref: ${{ github.event.inputs.sourcecode }}
      # Remove existing locale/ja directory if it exists
      - name: Remove existing locale/ja if exists
        run: |
          rm -rf locale/ja
      # Checkout Japanese locale source
      - name: Checkout iroha-one/odoo-docs-src-locale-ja
        uses: actions/checkout@v3
        with:
          repository: iroha-one/odoo-docs-locale-ja-${{ github.event.inputs.sourcecode }}
          ref: ${{ github.event.inputs.branch }}
          path: locale/ja
      # Install Python and required OS packages
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ github.event.inputs.python-version }}
      - name: Install additional OS packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libldap2-dev libsasl2-dev
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      # Optionally checkout odoo/odoo repository
      - name: Checkout odoo/odoo
        if: ${{ github.event.inputs.checkout_odoo == 'true' }}
        uses: actions/checkout@v3
        with:
          repository: odoo/odoo
          ref: ${{ github.event.inputs.sourcecode }}
          path: odoo
      - name: Install odoo/odoo dependencies
        if: ${{ github.event.inputs.checkout_odoo == 'true' }}
        run: |
          pip install -r odoo/requirements.txt
      # Create _build/html/ja directory if it doesn't exist
      - name: Create _build/html/ja directory
        run: |
          mkdir -p _build/html/ja
      # Update locale/sources and export to _build/html/ja/lc_sources.zip
      - name: Run make gettext
        run: |
          make gettext
      - name: Zip locale/sources to _build/html/ja/lc_sources.zip
        run: |
          zip -r _build/html/ja/lc_sources.zip locale/sources
      # Build Sphinx documentation for Japanese locale
      - name: Add 'ja' to languages_names in conf.py
        run: |
          echo -e "\n\nlanguages_names['ja']='日本語'\n" >> conf.py
      - name: Build Sphinx docs
        run: |
          make html 2>&1 | tee _build/html/ja/build.log
        env:
          CURRENT_LANG: ja
      # Deploy to GitHub Pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/ja/

# You can also use this Sphinx build action:
# https://github.com/marketplace/actions/sphinx-build
