# From:
# https://github.com/rkdarst/sphinx-actions-test/blob/master/.github/workflows/sphinx-build.yml

# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: sphinx
# on: [push, pull_request]
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: true
        default: '14.0-l10n-ja'
        type: choice
        options:
        - '14.0-l10n-ja'
        - '14.0'
        - '15.0'
      sourcecode:
        description: 'With inline docstrings'
        required: true
        default: '14.0' 
        type: choice
        options:
        - '14.0'
        - '15.0'

# https://gist.github.com/c-bata/ed5e7b7f8015502ee5092a3e77937c99
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout odoo/documentation
        uses: actions/checkout@v3
        with:
          repository: iroha-one/odoo-doc
          ref: ${{ github.event.inputs.branch }}
      - name: Checkout odoo/odoo
        uses: actions/checkout@v3
        with:
          repository: odoo/odoo
          ref: ${{ github.event.inputs.sourcecode }}
          path: odoo
      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # I don't know where the "run" thing is documented.
      - name: Install additional OS packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libldap2-dev libsasl2-dev
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install dependencies of odoo/odoo
        run: |
          pip install -r odoo/requirements.txt
      - name: Build Sphinx docs
        run: |
          make html
        env:
          CURRENT_LANG: ja
      # https://github.com/marketplace/actions/github-pages
      #- if: success()
      #  uses: crazy-max/ghaction-github-pages@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    target_branch: gh-pages
      #    build_dir: _build/html/

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/ja/


# This action probably does everything for you:
# https://github.com/marketplace/actions/sphinx-build
